### ISSUE TITLE
Some suggestions 

### ISSUE THREAD

**Issue by NeedToLearn101** [AndreasBomholtz/Underboss#7]
hey Andreas,

I see you're still updating it I know how challenging it could be lol, I had my try with autohotkey and built some big scripts haha

I have some suggestions that would be amazing to add in your bot:

- a way to auto collect stamps from Queen's finance office, to sell 3k kickbacks bundles (best value offer)

- a way to upgrade advisors automatically using the available decrees there and toggle it off to prevent it from upgrading low level advisors with high level decrees(maybe a drop down menu for the maximum decree level or built-in like you do with building), something like that, usually that would be decrees 20+ because till decree +19 can  be farmed (maybe that can be changed later on), and from 0 to 10 can be upgraded without decrees at all, also to serve time whenever an advisor is arrested.

- a way to add desired advisors like marching/decrease build advisors in a folder or a quick way to deploy all 3 with a click of a button(or uk, the fastest way because the game can get laggy).

- a way to watch ads automatically from watch& earn that can restart the watching process if no ads are showing and collect box when 5 ads are done watching

- a new tab to open bundles, troop bundles (either built-in or selective) and misc

If you need an account to test it out lemme know

P.S: my offer still stands, you're welcome to join my crew anytime :)
maybe the game gets you interested xD

Best Regards
MT8

**Comment by AndreasBomholtz** [comment]
Hey,

Thanks for the suggestions, I will look into if I can automate them :)

I'm playing on the Corozzo server right now. What server are you on?

**Comment by NeedToLearn101** [comment]
I'm on Masseria

**Comment by AndreasBomholtz** [comment]
Okay, I will. My nick is NeoGeo.

**Comment by AndreasBomholtz** [comment]
hmm, the game just assigned me a random familie :( So I have to wait until I get a "Change Familie" until I can join...

**Comment by NeedToLearn101** [comment]
sorry for my late reply, I have been busy and totally forgot to reply

I didn't know that the game implemented that weird system...that's very unhandy...weird

if you have line messenger app so I can contact you through it, maybe I can get you an account that's already in our family

my line id is: mercy.main.btw

**Comment by AndreasBomholtz** [comment]
I have added Financier Office Support. I will split your other suggestions into other issues.
